---

- name: package installation
  apt:
    name: "{{ ntp_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: disable monlist
  lineinfile:
    path: /etc/ntp.conf
    line: 'disable monitor'
  notify: restart ntp
  when: not ansible_check_mode

- name: enable and start service
  service:
    name: "{{ ntp_service_name }}"
    state: started
    enabled: yes
